select
     "EMAILER_EVENTS"."ID", "EMAILER_EVENTS"."RECIPIENT", "EMAILER_EVENTS"."CC", "EMAILER_EVENTS"."BCC", "EMAILER_EVENTS"."SUBJECT_PARAMETERS", "EMAILER_EVENTS"."SENT",
      "EMAILER_EVENTS"."DELIVERY_REPORT_DATE", "EMAILER_EVENTS"."DELIVERY_REPORT_EMAILS", "EMAILER_EVENTS"."DELIVERY_REPORT_SENT", "EMAILER_EVENTS"."EMAILER_TEMPLATE_ID"
       from "EMAILER_EVENTS" 
       where 
       "DELIVERY_REPORT_SENT" is null and "DELIVERY_REPORT_DATE" < TO_DATE('2023-11-05 10:54:26', 'YYYY/MM/DD HH24:MI:SS')