select 
"VU_WEB_LAD"."SECND_TRNS_CLSS", 
"VU_WEB_LAD"."SECND_TRNS_CLSS_NAME", 
"VU_WEB_LAD"."EVNT_DATE", 
"VU_WEB_LAD"."ORDR_NBR", 
"VU_WEB_LAD"."DFLT_STRM_CODE", 
"VU_WEB_LAD"."DFLT_STRM_NAME", 
"VU_WEB_LAD"."DFLT_TO_STRM_CODE", 
"VU_WEB_LAD"."DFLT_TO_STRM_NAME", 
"VU_WEB_LAD"."TRNS_STAT", 
"VU_WEB_LAD"."DOC_NBR", 
"VU_WEB_LAD"."DFLT_STRM_CODE", 
"VU_WEB_YADS_LTA_331"."FROM_DOC", 
"VU_WEB_YADS_LTA_331"."TO_DOC", 
"VU_WEB_YADS_LTA_331"."FROM_SECND_TRNS_CLSS", 
"VU_WEB_YADS_LTA_331"."TRNS_CLSS_NAME", 
"VU_WEB_YADS_LTA_331"."TO_SECND_TRNS_CLSS", 
"VU_WEB_YADS_LTA_331"."TO_TRNS_CLSS_NAME", 
"VU_WEB_YADS_LTA_331"."TO_LINE_TO_STRM_CODE", 
"LGSTC_ACTL_DOCS"."DOC_RMRK" 
from "VU_WEB_LAD" inner join
 "VU_WEB_YADS_LTA_331" on 
 ("VU_WEB_LAD"."FIRM_CODE" = "VU_WEB_YADS_LTA_331"."FIRM_CODE" 
 and "VU_WEB_LAD"."PRMY_TRNS_CLSS" = "VU_WEB_YADS_LTA_331"."FROM_PRMY_TRNS_CLSS" 
 and "VU_WEB_LAD"."DOC_NBR" = "VU_WEB_YADS_LTA_331"."FROM_DOC") 
 inner join "LGSTC_ACTL_DOCS" on 
 ("VU_WEB_LAD"."FIRM_CODE" = "LGSTC_ACTL_DOCS"."FIRM_CODE" 
 and "VU_WEB_LAD"."PRMY_TRNS_CLSS" = "LGSTC_ACTL_DOCS"."PRMY_TRNS_CLSS" 
 and "VU_WEB_LAD"."SECND_TRNS_CLSS" = "LGSTC_ACTL_DOCS"."SECND_TRNS_CLSS" 
 and "VU_WEB_LAD"."DOC_NBR" = "LGSTC_ACTL_DOCS"."DOC_NBR") 
 where "VU_WEB_LAD"."FIRM_CODE" = :1 
 and "VU_WEB_LAD"."PRMY_TRNS_CLSS" = :2 
 and "VU_WEB_LAD"."DOC_NBR" = :3